name: Build and Deploy

# on:
#  push:
#    branches:
#      - master

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    environment:
      name: production 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      run: |
        docker build -f src/LandsatReflectance.Api/Dockerfile --no-cache -t chronoalpha/fs_landsat_api .
    
    - name: Push the Docker image
      run: |
        docker push chronoalpha/fs_landsat_api

    - name: Trigger re-deploy webhook
      run: |
        curl --location '${{ secrets.LANDSAT_API_RENDER_DEPLOY_HOOK }}'

  deploy_ui:
    runs-on: ubuntu-latest
    environment:
      name: production 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      run: |
        docker build -f src/LandsatReflectance.UI/Dockerfile --no-cache -t chronoalpha/landsat_ui .
    
    - name: Push the Docker image
      run: |
        docker push chronoalpha/landsat_ui

    - name: Trigger re-deploy webhook
      run: |
        curl --location '${{ secrets.LANDSAT_UI_RENDER_DEPLOY_HOOK }}'
