name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  setup_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

  deploy_api:
    runs-on: ubuntu-latest
    needs: setup_docker
    environment:
      name: production 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        docker build -f LandsatReflectance.Api/Dockerfile --no-cache -t chronoalpha/fs_landsat_api .
    
    - name: Push the Docker image
      run: |
        docker push chronoalpha/fs_landsat_api

    - name: Trigger re-deploy webhook
      run: |
        curl --location '${{ secrets.LANDSAT_API_RENDER_DEPLOY_HOOK }}'

  deploy_ui:
    runs-on: ubuntu-latest
    needs: setup_docker
    environment:
      name: production 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        docker build -f LandsatReflectance.UI/Dockerfile --no-cache -t chronoalpha/landsat_ui .
    
    - name: Push the Docker image
      run: |
        docker push chronoalpha/landsat_ui

    - name: Trigger re-deploy webhook
      run: |
        curl --location '${{ secrets.LANDSAT_UI_RENDER_DEPLOY_HOOK }}'
